Repository uninus-opensource/uin-hackathon, pull requests merged in 2024-02, with the labels that each got.

#3 bugfix: can't build api backoffice
  apps/api/backoffice/src/app/app.module.ts
  apps/api/backoffice/src/main.ts
  apps/web/backoffice/package-lock.json
  apps/web/backoffice/package.json
  libs/api/.eslintrc.json
  libs/api/README.md
  libs/api/package.json
  libs/api/project.json
  libs/api/src/activity/controllers/activity.controller.ts
  libs/api/src/activity/modules/activity.module.ts
  libs/api/src/auth/controllers/auth.controller.ts
  libs/api/src/auth/modules/auth.module.ts
  libs/api/src/proposal/controllers/proposal.controller.ts
  libs/api/src/proposal/modules/proposal.module.ts
  libs/api/src/trpc/modules/trpc.module.ts
  libs/api/src/user/controllers/user.controller.ts
  libs/api/src/user/modules/user.module.ts
  libs/trpc/.eslintrc.json
  libs/trpc/README.md
  libs/trpc/package.json
  libs/trpc/project.json
  libs/trpc/src/lib/trpc.ts
  package-lock.json
Labels: bug

#4 Improvement: service drizzle
  apps/api/backoffice/.env.example
  apps/api/backoffice/src/app/app.module.ts
  apps/api/backoffice/src/main.ts
  libs/api/package.json
  libs/api/src/activity/controllers/activity.controller.spec.ts
  libs/api/src/activity/modules/activity.module.ts
  libs/api/src/activity/services/activity.service.spec.ts
  libs/api/src/activity/services/activity.service.ts
  libs/api/src/auth/controllers/auth.controller.ts
  libs/api/src/auth/modules/auth.module.ts
  libs/api/src/auth/services/auth.service.ts
  libs/api/src/common/guards/access.guard.ts
  libs/api/src/common/guards/google.guard.ts
  libs/api/src/common/guards/index.ts
  libs/api/src/common/guards/refresh.guard.ts
  libs/api/src/common/index.ts
  libs/api/src/common/models/migrations/0000_adorable_rogue.sql
  libs/api/src/common/models/migrations/0001_legal_earthquake.sql
  libs/api/src/common/models/migrations/0002_same_tigra.sql
  libs/api/src/common/models/migrations/0003_serious_scream.sql
  libs/api/src/common/models/migrations/0004_black_groot.sql
  libs/api/src/common/models/migrations/meta/0000_snapshot.json
  libs/api/src/common/models/migrations/meta/0001_snapshot.json
  libs/api/src/common/models/migrations/meta/0002_snapshot.json
  libs/api/src/common/models/migrations/meta/0003_snapshot.json
  libs/api/src/common/models/migrations/meta/0004_snapshot.json
  libs/api/src/common/models/migrations/meta/_journal.json
  libs/api/src/common/models/schema.ts
  libs/api/src/common/models/seed.ts
  libs/api/src/common/strategies/access.strategy.ts
  libs/api/src/common/strategies/google.strategy.ts
  libs/api/src/common/strategies/index.ts
  libs/api/src/common/strategies/refresh.strategy.ts
  libs/api/src/common/utilities/index.ts
  libs/api/src/common/utilities/jwt.ts
  libs/api/src/common/utilities/password.ts
  libs/api/src/drizzle/index.ts
  libs/api/src/drizzle/modules/drizzle.module.ts
  libs/api/src/drizzle/modules/index.ts
  libs/api/src/index.ts
  libs/api/src/proposal/controllers/proposal.controller.ts
  libs/api/src/proposal/services/proposal.service.ts
  libs/api/src/user/controllers/user.controller.ts
  libs/api/src/user/services/user.service.ts
  libs/entities/.eslintrc.json
  libs/entities/README.md
  libs/entities/package.json
  libs/entities/project.json
  libs/entities/src/auth.type.ts
  libs/entities/src/index.ts
  libs/entities/src/lib/entities.ts
  libs/entities/src/user.type.ts
  package-lock.json
  package.json
Labels: bug, enhancement

#9 Improvement: rest version
  apps/api/backoffice/src/app/app.module.ts
  apps/api/backoffice/src/main.ts
  apps/web/backoffice/app/api/trpc/[trpc]/route.ts
  apps/web/backoffice/package-lock.json
  apps/web/backoffice/pnpm-lock.yaml
  apps/web/landing/pnpm-lock.yaml
  drizzle.config.ts
  libs/api/package.json
  libs/api/src/activity/controllers/index.ts
  libs/api/src/activity/index.ts
  libs/api/src/activity/modules/index.ts
  libs/api/src/activity/routers/index.ts
  libs/api/src/activity/services/activity.service.ts
  libs/api/src/activity/services/index.ts
  libs/api/src/auth/controllers/index.ts
  libs/api/src/auth/index.ts
  libs/api/src/auth/modules/index.ts
  libs/api/src/auth/routers/index.ts
  libs/api/src/auth/services/index.ts
  libs/api/src/common/filters/http-exception.filter.ts
  libs/api/src/common/filters/index.ts
  libs/api/src/common/guards/access/index.ts
  libs/api/src/common/guards/google/index.ts
  libs/api/src/common/guards/index.ts
  libs/api/src/common/guards/permission/index.ts
  libs/api/src/common/guards/refresh/index.ts
  libs/api/src/common/index.ts
  libs/api/src/common/models/schema/index.ts
  libs/api/src/common/pipes/index.ts
  libs/api/src/common/pipes/zod/index.ts
  libs/api/src/common/strategies/access/index.ts
  libs/api/src/common/strategies/google/index.ts
  libs/api/src/common/strategies/index.ts
  libs/api/src/common/strategies/refresh/index.ts
  libs/api/src/common/utilities/jwt/index.ts
  libs/api/src/common/utilities/password/index.ts
  libs/api/src/drizzle/modules/drizzle.module.ts
  libs/api/src/drizzle/modules/index.ts
  libs/api/src/trpc/routers/trpc.router.ts
  libs/api/src/user/controllers/index.ts
  libs/api/src/user/modules/index.ts
  libs/api/src/user/routers/index.ts
  libs/api/src/user/services/index.ts
  libs/entities/src/index.ts
  libs/entities/src/schemas/activity/index.ts
  libs/entities/src/schemas/auth/index.ts
  libs/entities/src/schemas/index.ts
  libs/entities/src/schemas/user/index.ts
  libs/entities/src/types/common/index.ts
  libs/trpc/package.json
  package-lock.json
  package.json
Labels: enhancement

#10 feat: email service
  apps/api/backoffice/.env.example
  apps/api/backoffice/src/app/app.module.ts
  apps/web/backoffice/package-lock.json
  libs/api/package.json
  libs/api/src/auth/controllers/index.ts
  libs/api/src/auth/services/auth.service.ts
  libs/api/src/auth/services/index.ts
  libs/api/src/common/templates/email/index.ts
  libs/api/src/common/templates/index.ts
  libs/api/src/common/utilities/index.ts
  libs/api/src/common/utilities/otp/index.ts
  libs/api/src/email/index.ts
  libs/api/src/email/modules/index.ts
  libs/api/src/email/services/index.ts
  libs/api/src/index.ts
  libs/api/src/user/index.ts
  libs/api/src/user/services/index.ts
  libs/api/src/user/services/user.service.ts
  libs/entities/src/index.ts
  libs/entities/src/templates/email/index.ts
  libs/entities/src/templates/index.ts
  libs/entities/src/types/auth/index.ts
  package-lock.json
  package.json
Labels: enhancement

#12 feat: api chart activity
  apps/api/backoffice/.env.example
  apps/api/backoffice/src/app/app.module.ts
  apps/web/backoffice/package-lock.json
  apps/web/backoffice/package.json
  apps/web/landing/pnpm-lock.yaml
  libs/api/package.json
  libs/api/src/activity/controllers/index.ts
  libs/api/src/activity/services/index.ts
  libs/api/src/auth/modules/index.ts
  libs/api/src/auth/services/index.ts
  libs/api/src/common/models/migrations/0000_adorable_rogue.sql
  libs/api/src/common/models/migrations/0000_superb_mandroid.sql
  libs/api/src/common/models/migrations/0001_legal_earthquake.sql
  libs/api/src/common/models/migrations/0002_same_tigra.sql
  libs/api/src/common/models/migrations/0003_serious_scream.sql
  libs/api/src/common/models/migrations/0004_black_groot.sql
  libs/api/src/common/models/migrations/meta/0000_snapshot.json
  libs/api/src/common/models/migrations/meta/0001_snapshot.json
  libs/api/src/common/models/migrations/meta/0002_snapshot.json
  libs/api/src/common/models/migrations/meta/0003_snapshot.json
  libs/api/src/common/models/migrations/meta/0004_snapshot.json
  libs/api/src/common/models/migrations/meta/_journal.json
  libs/api/src/common/models/schema.ts
  libs/api/src/common/models/schema/index.ts
  libs/api/src/common/models/seed.ts
  libs/api/src/email/modules/index.ts
  libs/api/src/file/controllers/index.ts
  libs/api/src/file/index.ts
  libs/api/src/file/modules/index.ts
  libs/api/src/file/services/index.ts
  libs/api/src/index.ts
  libs/api/src/user/controllers/index.ts
  libs/api/src/user/services/index.ts
  libs/entities/src/enums/activity/index.ts
  libs/entities/src/enums/chart/index.ts
  libs/entities/src/enums/index.ts
  libs/entities/src/enums/organization/index.ts
  libs/entities/src/enums/permission/index.ts
  libs/entities/src/schemas/auth/index.ts
  libs/entities/src/types/activity/index.ts
  libs/entities/src/types/auth/index.ts
  libs/entities/src/types/chart/index.ts
  libs/entities/src/types/common/index.ts
  libs/entities/src/types/file/index.ts
  libs/entities/src/types/index.ts
  libs/entities/src/types/user/index.ts
  package-lock.json
  package.json
Labels: bug, enhancement

#13 bugfix: api chart activity
  libs/api/src/activity/controllers/index.ts
  libs/api/src/activity/services/index.ts
  libs/api/src/common/strategies/access/index.ts
  libs/api/src/common/strategies/refresh/index.ts
  libs/entities/src/types/chart/index.ts
Labels: bug

#18 Impovement: swagger doc
  apps/api/backoffice/.env.example
  apps/api/backoffice/src/app/app.module.ts
  apps/api/backoffice/src/main.ts
  libs/api/package.json
  libs/api/src/activity/controllers/index.ts
  libs/api/src/auth/controllers/index.ts
  libs/api/src/common/dto/activity/index.ts
  libs/api/src/common/dto/auth/index.ts
  libs/api/src/common/dto/index.ts
  libs/api/src/common/dto/master/index.ts
  libs/api/src/common/dto/user/index.ts
  libs/api/src/common/index.ts
  libs/api/src/file/controllers/index.ts
  libs/api/src/master/organization/controllers/index.ts
  libs/api/src/master/role/controllers/index.ts
  libs/api/src/user/controllers/index.ts
  libs/entities/src/types/user/index.ts
  package-lock.json
  package.json
Labels: enhancement

#19 Improvement: api review activity
  apps/api/backoffice/src/app/app.controller.spec.ts
  apps/api/backoffice/src/app/app.controller.ts
  apps/api/backoffice/src/app/app.service.spec.ts
  apps/api/backoffice/src/app/app.service.ts
  apps/api/backoffice/src/app/index.ts
  apps/api/backoffice/src/app/module/index.spec.ts
  apps/api/backoffice/src/app/module/index.ts
  apps/api/backoffice/src/main.ts
  libs/api/src/activity/controllers/index.spec.ts
  libs/api/src/activity/controllers/index.ts
  libs/api/src/activity/services/index.ts
  libs/api/src/auth/controllers/index.ts
  libs/api/src/auth/services/index.ts
  libs/api/src/common/models/migrations/0000_strong_darkstar.sql
  libs/api/src/common/models/migrations/meta/0000_snapshot.json
  libs/api/src/common/models/migrations/meta/_journal.json
  libs/api/src/common/models/schema/index.ts
  libs/api/src/master/organization/controllers/index.ts
  libs/api/src/master/organization/services/index.ts
  libs/api/src/master/role/controllers/index.ts
  libs/api/src/user/controllers/index.ts
  libs/entities/src/types/activity/index.ts
  libs/entities/src/types/auth/index.ts
  libs/entities/src/types/common/index.ts
  libs/entities/src/types/organization/index.ts
Labels: enhancement

#27 feat: magic link verification email
  apps/api/backoffice/.env.example
  apps/api/backoffice/src/app/module/index.ts
  libs/api/src/auth/controllers/index.ts
  libs/api/src/auth/services/index.ts
  libs/api/src/common/guards/index.ts
  libs/api/src/common/guards/query/index.ts
  libs/api/src/common/models/migrations/0000_wooden_psylocke.sql
  libs/api/src/common/models/migrations/meta/0000_snapshot.json
  libs/api/src/common/models/migrations/meta/_journal.json
  libs/api/src/common/models/schema/index.ts
  libs/api/src/common/strategies/index.ts
  libs/api/src/common/strategies/query/index.ts
  libs/entities/src/templates/email/index.ts
Labels: enhancement

#31 bugfix: compare password
  apps/web/backoffice/package-lock.json
  apps/web/backoffice/package.json
  libs/api/src/activity/services/index.ts
  libs/api/src/auth/services/index.ts
  libs/api/src/common/models/schema/index.ts
  libs/api/src/master/department/controllers/index.ts
  libs/api/src/master/department/services/index.ts
  libs/api/src/master/faculty/controllers/index.ts
  libs/api/src/master/faculty/services/index.ts
  libs/api/src/master/organization/controllers/index.ts
  libs/api/src/master/organization/services/index.ts
  libs/api/src/master/role/controllers/index.ts
  libs/api/src/master/role/services/index.ts
  libs/api/src/user/services/index.ts
  libs/entities/src/types/master/index.ts
  package.json
Labels: bug

#33 feat : add component card & snackbar
  libs/web/components/atoms/src/card/card.spec.tsx
  libs/web/components/atoms/src/card/card.stories.tsx
  libs/web/components/atoms/src/card/card.tsx
  libs/web/components/atoms/src/card/index.ts
  libs/web/components/atoms/src/index.ts
  libs/web/components/atoms/src/snackbar/index.ts
  libs/web/components/atoms/src/snackbar/snackbar.stories.tsx
  libs/web/components/atoms/src/snackbar/snackbar.tsx
  libs/web/components/atoms/src/snackbar/type.ts
  libs/web/components/atoms/src/snackbar/utils.ts
  libs/web/components/atoms/tsconfig.spec.json
Labels: enhancement

#35 feat: forgot passowrd
  apps/web/backoffice/app/(auth)/auth/forgot/_modules/index.tsx
  apps/web/backoffice/app/(auth)/auth/forgot/_modules/wait/index.tsx
  apps/web/backoffice/app/(auth)/auth/forgot/page.tsx
  apps/web/backoffice/app/(auth)/auth/forgot/wait/page.tsx
  apps/web/backoffice/app/(auth)/auth/login/_modules/index.tsx
  apps/web/backoffice/app/(auth)/auth/reset/index.ts
  libs/web/auth/src/lib/web-auth.api.ts
  libs/web/auth/src/lib/web-auth.hook.ts
Labels: enhancement

#36 feat : slicing dashboard submission, activity,master data admin page
  apps/web/backoffice/app/(protected)/dashboard/(activity)/activity/_modules/index.tsx
  apps/web/backoffice/app/(protected)/dashboard/(activity)/activity/page.tsx
  apps/web/backoffice/app/(protected)/dashboard/(master)/master/admin/_modules/index.tsx
  apps/web/backoffice/app/(protected)/dashboard/(master)/master/admin/page.tsx
  apps/web/backoffice/app/(protected)/dashboard/(submission)/submission/_modules/index.tsx
  apps/web/backoffice/app/(protected)/dashboard/(submission)/submission/page.tsx
  libs/web/components/organisms/src/datatable/datatable.tsx
  libs/web/components/organisms/src/index.ts
  libs/web/components/organisms/src/modal/index.ts
  libs/web/components/organisms/src/modal/modal.spec.tsx
  libs/web/components/organisms/src/modal/modal.stories.tsx
  libs/web/components/organisms/src/modal/modal.tsx
Labels: enhancement

#38 feat: reset password
  apps/web/backoffice/app/(auth)/auth/reset/_modules/index.tsx
  apps/web/backoffice/app/(auth)/auth/reset/index.ts
  apps/web/backoffice/app/(auth)/auth/reset/page.tsx
  apps/web/backoffice/package-lock.json
  libs/web/auth/src/lib/web-auth.api.ts
  libs/web/auth/src/lib/web-auth.hook.ts
Labels: documentation, enhancement

#41 bugfix: reset password
  libs/api/src/auth/controllers/index.ts
  package-lock.json
  package.json
Labels: bug

#42 Improvement: oauth new method
  libs/api/package.json
  libs/api/src/auth/controllers/index.ts
  libs/api/src/auth/modules/index.ts
  libs/api/src/auth/services/index.ts
  libs/api/src/common/dto/auth/index.ts
  libs/api/src/common/strategies/google/index.ts
  libs/entities/src/schemas/auth/index.ts
  libs/entities/src/types/auth/index.ts
  package-lock.json
  package.json
Labels: enhancement
